### ISSUE TITLE
Mising Blocks on Update

### ISSUE THREAD

**Issue by cutter4ever** [cout970/Magneticraft-API-and-Insues#7]
When upgrading from version magneticraft-0.2.12 to magneticraft-0.3.4 there are 32 missing missing blocks in this save. Just want to know if this is going to kill my world ?

 Forge Mod Loader detected missing blocks/items.

There are 32 missing blocks and items in this save.
If you continue the missing blocks/items will get removed.
A world backup will be automatically created in your saves directory.

Missing Blocks/Items:
Magneticraft:heat_cable
Magneticraft:item.thoriumsand
Magneticraft:item.silversand
Magneticraft:item.coppersand
Magneticraft:item.tingravel
Magneticraft:item.leadsand
Magneticraft:item.zincgravel
Magneticraft:item.tinsand
Magneticraft:item.uraniumsand
Magneticraft:item.nickelgravel
Magneticraft:item.nickelsand
Magneticraft:item.uraniumgravel
Magneticraft:item.coppergravel
Magneticraft:item.zincsand
Magneticraft:item.aluminiumsand
Magneticraft:item.irongravel
Magneticraft:item.thoriumgravel
Magneticraft:item.dustUranium
Magneticraft:item.dustCopper
Magneticraft:item.leadgravel
Magneticraft:item.goldgravel
Magneticraft:item.tungstensand
Magneticraft:item.ironsand
Magneticraft:item.tungstengravel
Magneticraft:item.titaniumgravel
Magneticraft:item.goldsand
Magneticraft:heat_cable
Magneticraft:item.aluminiumgravel
Magneticraft:item.dustTungsten
Magneticraft:item.dustThorium
Magneticraft:item.silvergravel
Magneticraft:item.titaniumsand

Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.

**Comment by cout970** [comment]
This items have been replaced for a new ones, don't worry nothing in your world will break, this is only saying you that the items will disappear from the world. This items are from the old ore processing system.
