### ISSUE TITLE
Resource pack makes conveyers look like flowing purple liquid

### ISSUE THREAD

**Issue by TheQuantumGeneral** [cout970/Magneticraft-API-and-Insues#9]
I am using a custom Unity resource pack, it doesn't officially change any Magneticraft textures, but it makes conveyer belts looks like taint water. 
![2015-08-15_00 52 43](https://cloud.githubusercontent.com/assets/7843312/9276731/0eb2f18a-42e9-11e5-819a-d1735470f218.png)
![2015-08-15_00 52 58](https://cloud.githubusercontent.com/assets/7843312/9276732/0eb6da16-42e9-11e5-9d6c-fc82cbc0c2df.png)

**Comment by MechWarrior99** [comment]
Did you change anything with the unity resourceoack or with Magneticraft.?

**Comment by TheQuantumGeneral** [comment]
It is only a few unity modules, but otherwise all basic. No texture edits to Magneticraft

![capture](https://cloud.githubusercontent.com/assets/7843312/9289257/3018446e-43ad-11e5-8176-0121b138e386.PNG)

**Comment by MechWarrior99** [comment]
What if you take GalacticraftCore out?

**Comment by MechWarrior99** [comment]
Also i think it maybe UU-matter not taint water.

**Comment by TheQuantumGeneral** [comment]
Found the cause.

I use a custom water texture, and for whatever reason, when I use it, all the conveyer belts look like UU Matter.

Unity  water
![water_stil1l](https://cloud.githubusercontent.com/assets/7843312/9289380/e0ce48d2-43b0-11e5-8546-92424bf21b5d.png)
![water_flo1w](https://cloud.githubusercontent.com/assets/7843312/9289379/e0ce4c42-43b0-11e5-94ee-37c4925a8052.png)

My water
![water_still](https://cloud.githubusercontent.com/assets/7843312/9289381/e0cf3ba2-43b0-11e5-8090-06a397b4f7f3.png)
![water_flow](https://cloud.githubusercontent.com/assets/7843312/9289382/e0f1947c-43b0-11e5-9065-8279779645c0.png)

**Comment by MechWarrior99** [comment]
I have no idea why it would conflict :/

**Comment by TheQuantumGeneral** [comment]
Its not a big deal at least. I'll use vanilla water for now.
